### ISSUE TITLE
Can't install in nova 2.0

### ISSUE THREAD

**Issue by tuandev-nv** [DigitalCloud/nova-blog-tool#6]
Thank you for your package, 
Please upgrade this package to working with Nova 2.x !!!
Thanks !!!

**Comment by zamudio-fabian** [comment]
Hi, I give you a fork that I made and it works for me in Nova 2.0. 
I hope I help you
https://github.com/zamudio-fabian/nova-blog-tool/

**Comment by tuandev-nv** [comment]
@zamudio-fabian  thank you so much

**Comment by mohrajab** [comment]
Hi @zamudio-fabian , could you make it a pull request so we can merge it on the original package ?
Thank you for your contribution

**Comment by zamudio-fabian** [comment]
@mohrajab Request sent
